CHARMS = [
    "Gathering Swarm",
    "Wayward Compass",
    "Grubsong",
    "Stalwart Shell",
    "Baldur Shell",
    "Fury of the Fallen",
    "Quick Focus",
    "Lifeblood Heart",
    "Lifeblood Core",
    "Defenders Crest",
    "Flukenest",
    "Thorns of Agony",
    "Mark of Pride",
    "Steady Body",
    "Heavy Blow",
    "Sharp Shadow",
    "Spore Shroom",
    "Longnail",
    "Shaman Stone",
    "Soul Catcher",
    "Soul Eater",
    "Glowing Womb",
    "Fragile Heart",
    "Fragile Greed",
    "Fragile Strength",
    "Nailmasters Glory",
    "Jonis Blessing",
    "Shape of Unn",
    "Hiveblood",
    "Dream Wielder",
    "Dashmaster",
    "Quick Slash",
    "Spell Twister",
    "Deep Focus",
    "Grubberflys Elegy",
    "Void Heart",
    # The Grimm Troupe DLC
    "Sprintmaster",
    "Dreamshield",
    "Weaversong",
    "Carefree Melody"
]

# "Grimmchild / Carefree Melody"